"use strict";

function numericPredicate({
  predicate,
  label,
  comparator,
  threshold,
  scale,
  units,
  codes = [],
  keywords = [],
  excludes = [],
}) {
  return {
    predicate,
    label,
    type: "numeric",
    comparator,
    threshold,
    scale,
    units,
    codes,
    keywords,
    excludes,
  };
}

function negativePredicate({
  predicate,
  label,
  codes = [],
  keywords = [],
  excludes = [],
}) {
  return {
    predicate,
    label,
    type: "coded_negative",
    comparator: "negative",
    threshold: null,
    scale: 1,
    units: [],
    codes,
    keywords,
    excludes,
  };
}

const MG_DL = ["mg/dl"];
const PERCENT = ["%"];
const MM_HG = ["mm[hg]", "mmhg"];
const KG_M2 = ["kg/m2", "kg/m^2"];
const U_PER_L = ["u/l", "iu/l"];
const MMOL_L = ["mmol/l", "meq/l"];
const G_DL = ["g/dl"];
const UG_DL = ["ug/dl"];
const NG_ML = ["ng/ml"];
const PG_ML = ["pg/ml"];
const FL = ["fl"];
const MM_H = ["mm/h", "mm/hr"];
const SEC = ["s", "sec"];
const TSH_UNITS = ["miu/l", "uiu/ml", "u[IU]/mL", "u[IU]/ml", "mu/l"].map(
  (value) => value.toLowerCase(),
);
const CBC_WBC_UNITS = ["10*3/ul", "10^3/ul", "k/ul", "x10^3/ul"];
const CBC_RBC_UNITS = ["10*6/ul", "10^6/ul", "m/ul", "x10^6/ul"];
const EGFR_UNITS = [
  "ml/min/1.73m2",
  "ml/min/{1.73_m2}",
  "ml/min/1.73 m2",
];
const RATIO_UNITS = ["ratio", "{ratio}", "1"];

const BASE_PREDICATES = [
  negativePredicate({
    predicate: "HIV_NEGATIVE",
    label: "HIV",
    codes: ["56888-1"],
    keywords: [["hiv"]],
  }),
  negativePredicate({
    predicate: "HEPB_NEGATIVE",
    label: "Hepatitis B",
    codes: ["5196-1"],
    keywords: [["hepatitis", "b"], ["hepb"]],
  }),
  negativePredicate({
    predicate: "HEPC_NEGATIVE",
    label: "Hepatitis C",
    codes: ["13955-0"],
    keywords: [["hepatitis", "c"], ["hepc"]],
  }),
  negativePredicate({
    predicate: "COVID_NEGATIVE",
    label: "COVID-19",
    codes: ["94500-6"],
    keywords: [["covid"], ["sars", "cov", "2"]],
  }),
  negativePredicate({
    predicate: "PREGNANCY_NEGATIVE",
    label: "Pregnancy",
    codes: ["2106-3"],
    keywords: [["pregnancy"], ["hcg"]],
  }),
  numericPredicate({
    predicate: "HBA1C_LT_6_5",
    label: "HbA1c",
    comparator: "lt",
    threshold: 650,
    scale: 100,
    units: PERCENT,
    codes: ["4548-4"],
    keywords: [["hba1c"], ["hemoglobin", "a1c"], ["a1c"]],
  }),
  numericPredicate({
    predicate: "TOTAL_CHOLESTEROL_LT_200",
    label: "Total cholesterol",
    comparator: "lt",
    threshold: 2000,
    scale: 10,
    units: MG_DL,
    codes: ["2093-3"],
    keywords: [["total", "cholesterol"], ["cholesterol"]],
  }),
  numericPredicate({
    predicate: "LDL_LT_130",
    label: "LDL",
    comparator: "lt",
    threshold: 1300,
    scale: 10,
    units: MG_DL,
    codes: ["13457-7"],
    keywords: [["ldl"]],
  }),
  numericPredicate({
    predicate: "FASTING_GLUCOSE_LT_100",
    label: "Fasting glucose",
    comparator: "lt",
    threshold: 1000,
    scale: 10,
    units: MG_DL,
    codes: ["1558-6"],
    keywords: [["fasting", "glucose"]],
  }),
  numericPredicate({
    predicate: "TRIGLYCERIDES_LT_150",
    label: "Triglycerides",
    comparator: "lt",
    threshold: 1500,
    scale: 10,
    units: MG_DL,
    codes: ["2571-8"],
    keywords: [["triglycerides"], ["triglyceride"]],
  }),
  numericPredicate({
    predicate: "HDL_GT_40",
    label: "HDL",
    comparator: "gt",
    threshold: 400,
    scale: 10,
    units: MG_DL,
    codes: ["2085-9"],
    keywords: [["hdl"]],
  }),
  numericPredicate({
    predicate: "SYSTOLIC_BP_LT_130",
    label: "Systolic blood pressure",
    comparator: "lt",
    threshold: 1300,
    scale: 10,
    units: MM_HG,
    codes: ["8480-6"],
    keywords: [["systolic", "blood", "pressure"], ["systolic"]],
  }),
  numericPredicate({
    predicate: "DIASTOLIC_BP_LT_80",
    label: "Diastolic blood pressure",
    comparator: "lt",
    threshold: 800,
    scale: 10,
    units: MM_HG,
    codes: ["8462-4"],
    keywords: [["diastolic", "blood", "pressure"], ["diastolic"]],
  }),
  numericPredicate({
    predicate: "BMI_LT_30",
    label: "BMI",
    comparator: "lt",
    threshold: 300,
    scale: 10,
    units: KG_M2,
    codes: ["39156-5"],
    keywords: [["body", "mass", "index"], ["bmi"]],
  }),
  numericPredicate({
    predicate: "CREATININE_LT_1_3",
    label: "Creatinine",
    comparator: "lt",
    threshold: 13,
    scale: 10,
    units: MG_DL,
    codes: ["2160-0"],
    keywords: [["creatinine"]],
  }),

  negativePredicate({
    predicate: "SYPHILIS_NEGATIVE",
    label: "Syphilis",
    keywords: [["syphilis"]],
  }),
  negativePredicate({
    predicate: "GONORRHEA_NEGATIVE",
    label: "Gonorrhea",
    keywords: [["gonorrhea"], ["neisseria", "gonorrhoeae"]],
  }),
  negativePredicate({
    predicate: "CHLAMYDIA_NEGATIVE",
    label: "Chlamydia",
    keywords: [["chlamydia"], ["chlamydia", "trachomatis"]],
  }),
  negativePredicate({
    predicate: "HSV1_NEGATIVE",
    label: "HSV-1",
    keywords: [["hsv", "1"], ["herpes", "simplex", "1"]],
  }),
  negativePredicate({
    predicate: "HSV2_NEGATIVE",
    label: "HSV-2",
    keywords: [["hsv", "2"], ["herpes", "simplex", "2"]],
  }),
  negativePredicate({
    predicate: "HPV_NEGATIVE",
    label: "HPV",
    keywords: [["hpv"], ["human", "papillomavirus"]],
  }),
  negativePredicate({
    predicate: "INFLUENZA_A_NEGATIVE",
    label: "Influenza A",
    keywords: [["influenza", "a"], ["flu", "a"]],
  }),
  negativePredicate({
    predicate: "INFLUENZA_B_NEGATIVE",
    label: "Influenza B",
    keywords: [["influenza", "b"], ["flu", "b"]],
  }),
  negativePredicate({
    predicate: "RSV_NEGATIVE",
    label: "RSV",
    keywords: [["rsv"], ["respiratory", "syncytial"]],
  }),
  negativePredicate({
    predicate: "TUBERCULOSIS_NEGATIVE",
    label: "Tuberculosis",
    keywords: [["tuberculosis"], ["tb"]],
  }),
  negativePredicate({
    predicate: "EBV_NEGATIVE",
    label: "EBV",
    keywords: [["ebv"], ["epstein", "barr"]],
  }),
  negativePredicate({
    predicate: "CMV_NEGATIVE",
    label: "CMV",
    keywords: [["cmv"], ["cytomegalovirus"]],
  }),
  negativePredicate({
    predicate: "RUBELLA_IGM_NEGATIVE",
    label: "Rubella IgM",
    keywords: [["rubella", "igm"]],
  }),
  negativePredicate({
    predicate: "TOXOPLASMA_IGM_NEGATIVE",
    label: "Toxoplasma IgM",
    keywords: [["toxoplasma", "igm"]],
  }),
  negativePredicate({
    predicate: "H_PYLORI_NEGATIVE",
    label: "H. pylori",
    keywords: [["h", "pylori"], ["helicobacter", "pylori"]],
  }),

  numericPredicate({
    predicate: "GLUCOSE_RANDOM_LT_140",
    label: "Random glucose",
    comparator: "lt",
    threshold: 1400,
    scale: 10,
    units: MG_DL,
    keywords: [["random", "glucose"]],
  }),
  numericPredicate({
    predicate: "GLUCOSE_RANDOM_LT_200",
    label: "Random glucose",
    comparator: "lt",
    threshold: 2000,
    scale: 10,
    units: MG_DL,
    keywords: [["random", "glucose"]],
  }),
  numericPredicate({
    predicate: "HBA1C_LT_5_7",
    label: "HbA1c",
    comparator: "lt",
    threshold: 570,
    scale: 100,
    units: PERCENT,
    keywords: [["hba1c"], ["hemoglobin", "a1c"], ["a1c"]],
  }),
  numericPredicate({
    predicate: "HBA1C_LT_8_0",
    label: "HbA1c",
    comparator: "lt",
    threshold: 800,
    scale: 100,
    units: PERCENT,
    keywords: [["hba1c"], ["hemoglobin", "a1c"], ["a1c"]],
  }),
  numericPredicate({
    predicate: "INSULIN_FASTING_LT_25",
    label: "Fasting insulin",
    comparator: "lt",
    threshold: 250,
    scale: 10,
    units: ["uiu/ml", "u[iu]/ml", "miu/l", "uiu/l"],
    keywords: [["fasting", "insulin"], ["insulin"]],
  }),
  numericPredicate({
    predicate: "UREA_LT_50",
    label: "Urea",
    comparator: "lt",
    threshold: 500,
    scale: 10,
    units: MG_DL,
    keywords: [["urea"]],
  }),
  numericPredicate({
    predicate: "BUN_LT_20",
    label: "BUN",
    comparator: "lt",
    threshold: 200,
    scale: 10,
    units: MG_DL,
    keywords: [["bun"], ["urea", "nitrogen"]],
  }),
  numericPredicate({
    predicate: "EGFR_GT_60",
    label: "eGFR",
    comparator: "gt",
    threshold: 600,
    scale: 10,
    units: EGFR_UNITS,
    keywords: [["egfr"], ["glomerular", "filtration", "rate"]],
  }),
  numericPredicate({
    predicate: "URIC_ACID_LT_7_0",
    label: "Uric acid",
    comparator: "lt",
    threshold: 70,
    scale: 10,
    units: MG_DL,
    keywords: [["uric", "acid"]],
  }),
  numericPredicate({
    predicate: "MICROALBUMIN_LT_30",
    label: "Microalbumin",
    comparator: "lt",
    threshold: 300,
    scale: 10,
    units: ["mg/l"],
    keywords: [["microalbumin"], ["urine", "albumin"]],
  }),

  numericPredicate({
    predicate: "AST_LT_40",
    label: "AST",
    comparator: "lt",
    threshold: 400,
    scale: 10,
    units: U_PER_L,
    keywords: [["ast"], ["aspartate", "aminotransferase"]],
  }),
  numericPredicate({
    predicate: "ALT_LT_40",
    label: "ALT",
    comparator: "lt",
    threshold: 400,
    scale: 10,
    units: U_PER_L,
    keywords: [["alt"], ["alanine", "aminotransferase"]],
  }),
  numericPredicate({
    predicate: "ALP_LT_120",
    label: "ALP",
    comparator: "lt",
    threshold: 1200,
    scale: 10,
    units: U_PER_L,
    keywords: [["alp"], ["alkaline", "phosphatase"]],
  }),
  numericPredicate({
    predicate: "GGT_LT_60",
    label: "GGT",
    comparator: "lt",
    threshold: 600,
    scale: 10,
    units: U_PER_L,
    keywords: [["ggt"], ["gamma", "glutamyl"]],
  }),
  numericPredicate({
    predicate: "TOTAL_BILIRUBIN_LT_1_2",
    label: "Total bilirubin",
    comparator: "lt",
    threshold: 12,
    scale: 10,
    units: MG_DL,
    keywords: [["total", "bilirubin"], ["bilirubin"]],
  }),
  numericPredicate({
    predicate: "DIRECT_BILIRUBIN_LT_0_3",
    label: "Direct bilirubin",
    comparator: "lt",
    threshold: 3,
    scale: 10,
    units: MG_DL,
    keywords: [["direct", "bilirubin"], ["conjugated", "bilirubin"]],
  }),
  numericPredicate({
    predicate: "ALBUMIN_GT_3_5",
    label: "Albumin",
    comparator: "gt",
    threshold: 35,
    scale: 10,
    units: G_DL,
    keywords: [["albumin"]],
  }),
  numericPredicate({
    predicate: "TOTAL_PROTEIN_GT_6_0",
    label: "Total protein",
    comparator: "gt",
    threshold: 60,
    scale: 10,
    units: G_DL,
    keywords: [["total", "protein"]],
  }),
  numericPredicate({
    predicate: "AMMONIA_LT_50",
    label: "Ammonia",
    comparator: "lt",
    threshold: 500,
    scale: 10,
    units: UG_DL,
    keywords: [["ammonia"]],
  }),
  numericPredicate({
    predicate: "LDH_LT_250",
    label: "LDH",
    comparator: "lt",
    threshold: 2500,
    scale: 10,
    units: U_PER_L,
    keywords: [["ldh"], ["lactate", "dehydrogenase"]],
  }),

  numericPredicate({
    predicate: "SODIUM_GT_135",
    label: "Sodium",
    comparator: "gt",
    threshold: 1350,
    scale: 10,
    units: MMOL_L,
    keywords: [["sodium"]],
  }),
  numericPredicate({
    predicate: "SODIUM_LT_145",
    label: "Sodium",
    comparator: "lt",
    threshold: 1450,
    scale: 10,
    units: MMOL_L,
    keywords: [["sodium"]],
  }),
  numericPredicate({
    predicate: "POTASSIUM_GT_3_5",
    label: "Potassium",
    comparator: "gt",
    threshold: 35,
    scale: 10,
    units: MMOL_L,
    keywords: [["potassium"]],
  }),
  numericPredicate({
    predicate: "POTASSIUM_LT_5_1",
    label: "Potassium",
    comparator: "lt",
    threshold: 51,
    scale: 10,
    units: MMOL_L,
    keywords: [["potassium"]],
  }),
  numericPredicate({
    predicate: "CHLORIDE_GT_98",
    label: "Chloride",
    comparator: "gt",
    threshold: 980,
    scale: 10,
    units: MMOL_L,
    keywords: [["chloride"]],
  }),
  numericPredicate({
    predicate: "CHLORIDE_LT_107",
    label: "Chloride",
    comparator: "lt",
    threshold: 1070,
    scale: 10,
    units: MMOL_L,
    keywords: [["chloride"]],
  }),
  numericPredicate({
    predicate: "CALCIUM_GT_8_5",
    label: "Calcium",
    comparator: "gt",
    threshold: 85,
    scale: 10,
    units: MG_DL,
    keywords: [["calcium"]],
  }),
  numericPredicate({
    predicate: "CALCIUM_LT_10_5",
    label: "Calcium",
    comparator: "lt",
    threshold: 105,
    scale: 10,
    units: MG_DL,
    keywords: [["calcium"]],
  }),
  numericPredicate({
    predicate: "MAGNESIUM_GT_1_7",
    label: "Magnesium",
    comparator: "gt",
    threshold: 17,
    scale: 10,
    units: MG_DL,
    keywords: [["magnesium"]],
  }),
  numericPredicate({
    predicate: "MAGNESIUM_LT_2_4",
    label: "Magnesium",
    comparator: "lt",
    threshold: 24,
    scale: 10,
    units: MG_DL,
    keywords: [["magnesium"]],
  }),
  numericPredicate({
    predicate: "PHOSPHATE_GT_2_5",
    label: "Phosphate",
    comparator: "gt",
    threshold: 25,
    scale: 10,
    units: MG_DL,
    keywords: [["phosphate"], ["phosphorus"]],
  }),
  numericPredicate({
    predicate: "PHOSPHATE_LT_4_5",
    label: "Phosphate",
    comparator: "lt",
    threshold: 45,
    scale: 10,
    units: MG_DL,
    keywords: [["phosphate"], ["phosphorus"]],
  }),
  numericPredicate({
    predicate: "BICARBONATE_GT_22",
    label: "Bicarbonate",
    comparator: "gt",
    threshold: 220,
    scale: 10,
    units: MMOL_L,
    keywords: [["bicarbonate"], ["total", "co2"]],
  }),
  numericPredicate({
    predicate: "BICARBONATE_LT_29",
    label: "Bicarbonate",
    comparator: "lt",
    threshold: 290,
    scale: 10,
    units: MMOL_L,
    keywords: [["bicarbonate"], ["total", "co2"]],
  }),
  numericPredicate({
    predicate: "ANION_GAP_LT_16",
    label: "Anion gap",
    comparator: "lt",
    threshold: 160,
    scale: 10,
    units: MMOL_L,
    keywords: [["anion", "gap"]],
  }),

  numericPredicate({
    predicate: "NON_HDL_LT_160",
    label: "Non-HDL cholesterol",
    comparator: "lt",
    threshold: 1600,
    scale: 10,
    units: MG_DL,
    keywords: [["non", "hdl"], ["non-hdl"]],
  }),
  numericPredicate({
    predicate: "NON_HDL_LT_130",
    label: "Non-HDL cholesterol",
    comparator: "lt",
    threshold: 1300,
    scale: 10,
    units: MG_DL,
    keywords: [["non", "hdl"], ["non-hdl"]],
  }),
  numericPredicate({
    predicate: "TOTAL_TO_HDL_RATIO_LT_5_0",
    label: "Total to HDL ratio",
    comparator: "lt",
    threshold: 50,
    scale: 10,
    units: RATIO_UNITS,
    keywords: [["total", "hdl", "ratio"], ["cholesterol", "hdl", "ratio"]],
  }),
  numericPredicate({
    predicate: "TOTAL_TO_HDL_RATIO_LT_4_0",
    label: "Total to HDL ratio",
    comparator: "lt",
    threshold: 40,
    scale: 10,
    units: RATIO_UNITS,
    keywords: [["total", "hdl", "ratio"], ["cholesterol", "hdl", "ratio"]],
  }),
  numericPredicate({
    predicate: "VLDL_LT_30",
    label: "VLDL",
    comparator: "lt",
    threshold: 300,
    scale: 10,
    units: MG_DL,
    keywords: [["vldl"]],
  }),
  numericPredicate({
    predicate: "APOB_LT_100",
    label: "ApoB",
    comparator: "lt",
    threshold: 1000,
    scale: 10,
    units: MG_DL,
    keywords: [["apob"], ["apolipoprotein", "b"]],
  }),
  numericPredicate({
    predicate: "APOA1_GT_120",
    label: "ApoA1",
    comparator: "gt",
    threshold: 1200,
    scale: 10,
    units: MG_DL,
    keywords: [["apoa1"], ["apolipoprotein", "a1"]],
  }),
  numericPredicate({
    predicate: "LIPOPROTEIN_A_LT_50",
    label: "Lipoprotein(a)",
    comparator: "lt",
    threshold: 500,
    scale: 10,
    units: MG_DL,
    keywords: [["lipoprotein", "a"], ["lp(a)"], ["lpa"]],
  }),
  numericPredicate({
    predicate: "HS_CRP_LT_3_0",
    label: "High-sensitivity CRP",
    comparator: "lt",
    threshold: 30,
    scale: 10,
    units: ["mg/l"],
    keywords: [["hs", "crp"], ["high", "sensitivity", "crp"]],
  }),
  numericPredicate({
    predicate: "BNP_LT_100",
    label: "BNP",
    comparator: "lt",
    threshold: 1000,
    scale: 10,
    units: PG_ML,
    keywords: [["bnp"], ["natriuretic", "peptide"]],
  }),

  numericPredicate({
    predicate: "HEMOGLOBIN_GT_12_0",
    label: "Hemoglobin",
    comparator: "gt",
    threshold: 120,
    scale: 10,
    units: G_DL,
    keywords: [["hemoglobin"], ["haemoglobin"]],
  }),
  numericPredicate({
    predicate: "HEMOGLOBIN_GT_13_0",
    label: "Hemoglobin",
    comparator: "gt",
    threshold: 130,
    scale: 10,
    units: G_DL,
    keywords: [["hemoglobin"], ["haemoglobin"]],
  }),
  numericPredicate({
    predicate: "HEMOGLOBIN_LT_17_5",
    label: "Hemoglobin",
    comparator: "lt",
    threshold: 175,
    scale: 10,
    units: G_DL,
    keywords: [["hemoglobin"], ["haemoglobin"]],
  }),
  numericPredicate({
    predicate: "HEMATOCRIT_GT_36",
    label: "Hematocrit",
    comparator: "gt",
    threshold: 360,
    scale: 10,
    units: PERCENT,
    keywords: [["hematocrit"], ["haematocrit"]],
  }),
  numericPredicate({
    predicate: "HEMATOCRIT_LT_52",
    label: "Hematocrit",
    comparator: "lt",
    threshold: 520,
    scale: 10,
    units: PERCENT,
    keywords: [["hematocrit"], ["haematocrit"]],
  }),
  numericPredicate({
    predicate: "WBC_GT_4_0",
    label: "WBC",
    comparator: "gt",
    threshold: 40,
    scale: 10,
    units: CBC_WBC_UNITS,
    keywords: [["wbc"], ["white", "blood", "cell"]],
  }),
  numericPredicate({
    predicate: "WBC_LT_11_0",
    label: "WBC",
    comparator: "lt",
    threshold: 110,
    scale: 10,
    units: CBC_WBC_UNITS,
    keywords: [["wbc"], ["white", "blood", "cell"]],
  }),
  numericPredicate({
    predicate: "PLATELETS_GT_150",
    label: "Platelets",
    comparator: "gt",
    threshold: 1500,
    scale: 10,
    units: CBC_WBC_UNITS,
    keywords: [["platelets"], ["platelet"]],
  }),
  numericPredicate({
    predicate: "PLATELETS_LT_450",
    label: "Platelets",
    comparator: "lt",
    threshold: 4500,
    scale: 10,
    units: CBC_WBC_UNITS,
    keywords: [["platelets"], ["platelet"]],
  }),
  numericPredicate({
    predicate: "RBC_GT_4_0",
    label: "RBC",
    comparator: "gt",
    threshold: 40,
    scale: 10,
    units: CBC_RBC_UNITS,
    keywords: [["rbc"], ["red", "blood", "cell"]],
  }),
  numericPredicate({
    predicate: "MCV_GT_80",
    label: "MCV",
    comparator: "gt",
    threshold: 800,
    scale: 10,
    units: FL,
    keywords: [["mcv"], ["mean", "corpuscular", "volume"]],
  }),
  numericPredicate({
    predicate: "MCV_LT_100",
    label: "MCV",
    comparator: "lt",
    threshold: 1000,
    scale: 10,
    units: FL,
    keywords: [["mcv"], ["mean", "corpuscular", "volume"]],
  }),
  numericPredicate({
    predicate: "RDW_LT_15",
    label: "RDW",
    comparator: "lt",
    threshold: 150,
    scale: 10,
    units: PERCENT,
    keywords: [["rdw"], ["red", "cell", "distribution", "width"]],
  }),
  numericPredicate({
    predicate: "NEUTROPHILS_LT_75",
    label: "Neutrophils",
    comparator: "lt",
    threshold: 750,
    scale: 10,
    units: PERCENT,
    keywords: [["neutrophils"], ["neutrophil"]],
  }),
  numericPredicate({
    predicate: "LYMPHOCYTES_GT_20",
    label: "Lymphocytes",
    comparator: "gt",
    threshold: 200,
    scale: 10,
    units: PERCENT,
    keywords: [["lymphocytes"], ["lymphocyte"]],
  }),

  numericPredicate({
    predicate: "ESR_LT_20",
    label: "ESR",
    comparator: "lt",
    threshold: 200,
    scale: 10,
    units: MM_H,
    keywords: [["esr"], ["erythrocyte", "sedimentation", "rate"]],
  }),
  numericPredicate({
    predicate: "CRP_LT_5",
    label: "CRP",
    comparator: "lt",
    threshold: 50,
    scale: 10,
    units: ["mg/l"],
    keywords: [["crp"], ["c-reactive", "protein"]],
    excludes: ["hs", "high sensitivity", "high-sensitivity"],
  }),
  numericPredicate({
    predicate: "FERRITIN_GT_30",
    label: "Ferritin",
    comparator: "gt",
    threshold: 300,
    scale: 10,
    units: NG_ML,
    keywords: [["ferritin"]],
  }),
  numericPredicate({
    predicate: "FERRITIN_LT_400",
    label: "Ferritin",
    comparator: "lt",
    threshold: 4000,
    scale: 10,
    units: NG_ML,
    keywords: [["ferritin"]],
  }),
  numericPredicate({
    predicate: "INR_LT_1_2",
    label: "INR",
    comparator: "lt",
    threshold: 12,
    scale: 10,
    units: [],
    keywords: [["inr"], ["international", "normalized", "ratio"]],
  }),
  numericPredicate({
    predicate: "PT_LT_14",
    label: "Prothrombin time",
    comparator: "lt",
    threshold: 140,
    scale: 10,
    units: SEC,
    keywords: [["prothrombin", "time"], ["pt"]],
  }),
  numericPredicate({
    predicate: "APTT_LT_35",
    label: "aPTT",
    comparator: "lt",
    threshold: 350,
    scale: 10,
    units: SEC,
    keywords: [
      ["aptt"],
      ["activated", "partial", "thromboplastin", "time"],
      ["partial", "thromboplastin", "time"],
    ],
  }),
  numericPredicate({
    predicate: "TSH_GT_0_4",
    label: "TSH",
    comparator: "gt",
    threshold: 4,
    scale: 10,
    units: TSH_UNITS,
    keywords: [["tsh"], ["thyroid", "stimulating", "hormone"]],
  }),
  numericPredicate({
    predicate: "TSH_LT_4_5",
    label: "TSH",
    comparator: "lt",
    threshold: 45,
    scale: 10,
    units: TSH_UNITS,
    keywords: [["tsh"], ["thyroid", "stimulating", "hormone"]],
  }),
  numericPredicate({
    predicate: "FREE_T4_GT_0_8",
    label: "Free T4",
    comparator: "gt",
    threshold: 8,
    scale: 10,
    units: ["ng/dl"],
    keywords: [["free", "t4"], ["free", "thyroxine"]],
  }),
];

const PREDICATES = BASE_PREDICATES.map((definition, index) => ({
  ...definition,
  index,
}));

const PREDICATE_COUNT = PREDICATES.length;

if (PREDICATE_COUNT !== 100) {
  throw new Error(`Expected 100 predicates, found ${PREDICATE_COUNT}`);
}

module.exports = {
  PREDICATES,
  PREDICATE_COUNT,
};
